version: "3"
services:
  bkc-node:
    image: bitkubchainorg/bkc-node-mainnet:2.1.0
    command:
      - "--syncmode=full"
      - "--gcmode=archive"
    environment:
      HOSTNAME: bkc-mainnet-archivenode
      STATS_SERVER: bkc-stats-server:3000
      STATS_PASSWORD: WelcomeToBitkubChain
    ports:
      - "30303:30303/udp"
      - "30303:30303"
      - "8545:8545"
      - "8546:8546"
    volumes:
      - "./data:/var/lib/bkc/data"
    restart: always
    stop_signal: SIGINT
    stop_grace_period: 60s
    healthcheck:
      test: curl --fail http://localhost:8545 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  
  bkc-stats-server:
    image: bitkubchainorg/bkc-stats-server:mainnet
    depends_on:
      - bkc-node
    environment:
      PORT: 3000
      WS_SECRET: WelcomeToBitkubChain
    ports:
      - "3000:3000"
    restart: always