{
 "title": "Bitkub Chain Node - Docker Dashbaord",
 "description": "Fixed queries and added network metrics. credit https://grafana.com/grafana/dashboards/5763",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "Container",
    "label": "Container",
    "query": "show tag values from docker_container_cpu with key=\"container_name\""
   },
   {
    "name": "dockerhost",
    "label": "Docker host",
    "query": "show tag values from docker with key=\"engine_host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Images count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_images" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "memory_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 1 },
   "targets": [
    {
     "alias": "Containers",
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    },
    {
     "alias": "Paused",
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_paused" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    },
    {
     "alias": "Stopped",
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_stopped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    },
    {
     "alias": "Running",
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    },
    {
     "alias": "Paused",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_paused" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    },
    {
     "alias": "Stopped",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_stopped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    },
    {
     "alias": "Running",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Recived",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    },
    {
     "alias": "Transmited",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    }
   ]
  },
  {
   "title": "$Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "repeat": "Container",
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Usage [%]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$Container$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    }
   ]
  },
  {
   "title": "IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "IO service recursive read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_read"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$Container$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    },
    {
     "alias": "IO service recursive write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_write"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$Container$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Usage [%]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$Container$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Recived",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$Container$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    },
    {
     "alias": "Transmited",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$Container$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$dockerhost$/" }
     ]
    }
   ]
  }
 ]
}