version: "3"
services:
  bkc-node:
    image: bitkubchainorg/node:latest
    entrypoint: /bkc-node/run-geth.sh
    command:
      - "--config=/bkc-node/config.toml"
      - "--datadir=/bkc-node/data"
      - "--syncmode=full"
      - "--gcmode=archive"
    environment:
      STATS_SERVER: ${STATS_SERVER}
      STATS_PASSWORD: ${STATS_PASSWORD}
      HOSTNAME: ${HOSTNAME}
    ports:
      - "30303:30303/udp"
      - "30303:30303"
      - "8545:8545"
      - "8546:8546"
    volumes:
      - "./genesis.json:/bkc-node/genesis.json"
      - "./config.toml:/bkc-node/config.toml"
      - "./data:/bkc-node/data"
      - "./run-geth.sh:/bkc-node/run-geth.sh"
    restart: always
    stop_signal: SIGINT
    stop_grace_period: 30s
    healthcheck:
      test: curl --fail http://localhost:8545 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  
  bkc-node-healthcheck:
    image: bitkubchainorg/bkc-node-healthcheck
    depends_on:
      - bkc-node
    environment:
      PORT: 8080
      RPC_URL: http://bkc-node:8545
      NETWORK_URLS: ${NETWORK_URLS}
    ports:
      - "8080:8080"
    restart: always
